services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - 3000:3000
  docs:
    build:
      context: .
      dockerfile: ./apps/docs/Dockerfile
    ports:
      - 3001:3000
